baseURL = "https://assomyharmony.org/"
googleAnalytics = "UA-175527980-1"
paginate = "4"
summaryLength = "30"
theme = "harmony"
title = "My Harmony | Association aide aux victimes"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 My Harmony Tous droits réservés"
languageCode = "en-us"
languageName = "En"
weight = 1
[[Languages.en.menu.footer]]
URL = "about"
name = "L'association"
weight = 1
[[Languages.en.menu.footer]]
URL = "service"
name = "Précarité Menstruelle"
weight = 3
[[Languages.en.menu.footer]]
URL = "blog"
name = "Blog"
weight = 4
[[Languages.en.menu.footer]]
URL = "contact"
name = "Contact"
weight = 6
[[Languages.en.menu.main]]
URL = ""
name = ""
weight = ""
[[Languages.en.menu.main]]
URL = "/"
name = "Accueil"
weight = 1
[[Languages.en.menu.main]]
URL = "/about"
name = "L’association"
weight = 2
[[Languages.en.menu.main]]
URL = "/précarité"
hasChildren = true
name = "Nos Actions"
weight = 4
[[Languages.en.menu.main]]
URL = "/mutilations"
name = "Mutilations génitales"
parent = "Nos Actions"
weight = 3
[[Languages.en.menu.main]]
URL = "/service"
name = "Précarité Menstruelle"
parent = "Nos Actions"
weight = 2
[[Languages.en.menu.main]]
URL = "/violences"
name = "Violences conjugales"
parent = "Nos Actions"
weight = 1
[[Languages.en.menu.main]]
URL = "blog"
name = "Blog"
weight = 5
[[Languages.en.menu.main]]
URL = "/contact"
name = "Nous Contacter"
weight = 7
[[Languages.en.menu.main]]
URL = "/dons"
name = "Appels aux dons"
weight = "7"
[Languages.fr]
contentDir = "content/french"
copyright = "Copyright &copy; 2020 [Themefisher](https://themefisher.com) All Rights Reserved"
languageCode = "fr-fr"
languageName = "Fr"
weight = 2
[[Languages.fr.menu.footer]]
URL = "about"
name = "About"
weight = 1
[[Languages.fr.menu.footer]]
URL = "project"
name = "Project"
weight = 2
[[Languages.fr.menu.footer]]
URL = "service"
name = "Service"
weight = 3
[[Languages.fr.menu.footer]]
URL = "pricing"
name = "Pricing"
weight = 4
[[Languages.fr.menu.footer]]
URL = "faq"
name = "FAQ"
weight = 5
[[Languages.fr.menu.footer]]
URL = "contact"
name = "Contact"
weight = 6
[[Languages.fr.menu.main]]
URL = "/"
name = "Accueil"
weight = 1
[[Languages.fr.menu.main]]
URL = "about"
name = "À propos"
weight = 2
[[Languages.fr.menu.main]]
URL = "project"
name = "Projet"
weight = 3
[[Languages.fr.menu.main]]
URL = "service"
name = "Un service"
weight = 4
[[Languages.fr.menu.main]]
URL = "blog"
name = "Blog"
weight = 5
[[Languages.fr.menu.main]]
URL = ""
hasChildren = true
name = "Pages"
weight = 6
[[Languages.fr.menu.main]]
URL = "faq"
name = "FAQ"
parent = "Pages"
weight = 6
[[Languages.fr.menu.main]]
URL = "pricing"
name = "Tarification"
parent = "Pages"
weight = 7
[[Languages.fr.menu.main]]
URL = "contact"
name = "Contact"
weight = 7
[params]
author = "Netary"
contact_form_action = "/merci"
description = ""
email = "associationmyharmony@gmail.com"
logo = "images/logo-mh.jpg"
mobile = "0124857985320"
multi_author = false
[params.gmap]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[params.nav_button]
enable = true
label = "Get A Quote"
link = "contact"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/lunar/lunar.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/lunar/lunar.js"
[[params.plugins.js]]
link = "plugins/lunar/popper.min.js"
[[params.plugins.js]]
link = "plugins/lunar/demo.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = ""
[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]
[[params.social]]
icon = "ion-social-googleplus-outline"
link = "#"
[[params.social]]
icon = "ion-social-linkedin-outline"
link = "#"
[[params.social]]
icon = "ion-social-pinterest-outline"
link = "#"
[[params.social]]
icon = "ion-social-dribbble-outline"
link = "#"
[[params.social]]
icon = "ion-social-twitter-outline"
link = "#https://twitter.com/myharmony3?s=11"
[[params.social]]
icon = "ion-social-facebook-outline"
link = "#"
